---
# These tasks pull the containers
- name: Pull db container
  shell: "docker pull {{item}}"
  with_items:
    - "{{ db_image }}:{{ db_version }}"
  when: install_docker_py|success

- name: Remove existing db container
  docker:
    name: "{{ db_container_name }}"
    image: "{{ db_image }}:{{ db_version }}"
    state: absent
  register: removed_db_container

- name: Start db container
  docker:
    name: "{{ db_container_name }}"
    image: "{{ db_image }}:{{ db_version }}"
    ports:
      - "{{ ansible_ssh_host }}:{{ db_port }}:{{ db_port }}"
    dns:
      - "{{ db_dns }}"
    env:
      USER: "{{ db_user }}"
      PASSWD: "{{ db_passwd }}"
    hostname: "{{ db_hostname }}"
    detach: True
    state: started
  when: removed_db_container|success
