rails:
  build: sumanmukherjee03/rails:onbuild
  links:
    - mysql
    - postgres
  ports:
    - "3000:3000"
  volumes:
    - "/Users/suman/Work/lp-webapp:/usr/src/app"
  environment:
    RAILS_ENV: development

postgres:
  image: sumanmukherjee03/postgres:9.1
  environment:
    PASSWD: welcome2psql

mysql:
  image: sumanmukherjee03/mysql:5.7
  environment:
    PASSWD: welcome2mysql

