- hosts: mysql
  gather_facts: True
  sudo: yes
  remote_user: developer

  tasks:
    - name: Install apt packages
      apt: "name='{{ item }}' state=present update_cache=yes install_recommends=no"
      with_items:
        - curl
        - git
        - python-pip

    - name: Install docker on host
      shell: >
        which docker ||
        curl -sSL https://get.docker.com/gpg | sudo apt-key add - &&
        curl -sSL https://get.docker.com/ | sh
      register: install_docker

    - name: Install docker-py
      pip: name=docker-py version=1.1.0
      register: install_docker_py
      when: install_docker|success

    - name: Pull mysql and consul containers
      shell: "docker pull {{item}}"
      with_items:
        - "sumanmukherjee03/mysql:5.7"
        - "sumanmukherjee03/consul:mysql"
      when: install_docker_py|success

    - name: Remove existing mysql container
      docker:
        name: mysqlServer
        image: "sumanmukherjee03/mysql:5.7"
        state: absent

    - name: Remove existing consul container
      docker:
        name: consulAgent
        image: "sumanmukherjee03/consul:mysql"
        state: absent

    - name: Start mysql container
      docker:
        name: mysqlServer
        image: "sumanmukherjee03/mysql:5.7"
        ports:
          - "{{ ansible_ssh_host }}:3306:3306"
        dns:
          - "172.20.20.10"
        env:
          USER: root
          PASSWD: welcome2mysql
        hostname: mysql
        detach: True
        pull: always
        state: restarted
        restart_policy: on-failure
        restart_policy_retry: 1
      register: mysql_container_result

    - name: Start consul container
      docker:
        name: consulAgent
        image: "sumanmukherjee03/consul:mysql"
        ports:
          - "{{ ansible_ssh_host }}:8600:53/udp"
          - "{{ ansible_ssh_host }}:8300:8300"
          - "{{ ansible_ssh_host }}:8301:8301"
          - "{{ ansible_ssh_host }}:8301:8301/udp"
          - "{{ ansible_ssh_host }}:8302:8302"
          - "{{ ansible_ssh_host }}:8302:8302/udp"
          - "{{ ansible_ssh_host }}:8400:8400"
          - "{{ ansible_ssh_host }}:8500:8500"
        links:
          - "mysqlServer:mysqlServer"
        dns:
          - "172.20.20.10"
        env:
          NODE_NAME: mysql_server
          EXTERNAL_IP: "{{ ansible_ssh_host }}"
          SERVICE_ID: mysqldb1
          SERVER: false
          JOIN_IP: 172.20.20.11
        hostname: mysql_server
        detach: True
        pull: always
        state: restarted
        restart_policy: on-failure
        restart_policy_retry: 1
      register: consul_container_result

    - debug: var=mysql_container_result
    - debug: var=consul_container_result
