database: &default
  adapter: <%= ENV['DB_ADAPTER'] || 'mysql2' %>
  encoding: utf8
  reconnect: false
  pool: 5
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
